// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: students.proto

package com.wkk.server.service.domain.grpc.student;

public final class StudentsOuterClass {
  private StudentsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_StudentId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_StudentId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_StudentsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_StudentsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_Students_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_Students_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_student_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_student_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016students.proto\022\007student\032\036google/protob" +
      "uf/wrappers.proto\032\033google/protobuf/empty" +
      ".proto\"\036\n\tStudentId\022\021\n\tstudentId\030\001 \001(\r\"\303" +
      "\001\n\017StudentsRequest\022,\n\006userId\030\001 \001(\0132\034.goo" +
      "gle.protobuf.StringValue\022*\n\004name\030\003 \001(\0132\034" +
      ".google.protobuf.StringValue\022)\n\003age\030\004 \001(" +
      "\0132\034.google.protobuf.UInt32Value\022+\n\005score" +
      "\030\005 \001(\0132\034.google.protobuf.UInt32Value\"-\n\010" +
      "Students\022!\n\007student\030\001 \003(\0132\020.student.Stud" +
      "ent\"K\n\007Student\022\n\n\002id\030\001 \001(\005\022\n\n\002no\030\002 \001(\t\022\014" +
      "\n\004name\030\003 \001(\t\022\013\n\003age\030\004 \001(\005\022\r\n\005score\030\005 \001(\005" +
      "2\333\001\n\013StudentsAPI\022A\n\022GetAllStudentsInfo\022\026" +
      ".google.protobuf.Empty\032\021.student.Student" +
      "s\"\000\022K\n\032GetStudentsInfoByCondition\022\030.stud" +
      "ent.StudentsRequest\032\021.student.Students\"\000" +
      "\022<\n\022GetStudentInfoById\022\022.student.Student" +
      "Id\032\020.student.Student\"\000B.\n*com.wkk.server" +
      ".service.domain.grpc.studentP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_student_StudentId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_student_StudentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_StudentId_descriptor,
        new String[] { "StudentId", });
    internal_static_student_StudentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_student_StudentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_StudentsRequest_descriptor,
        new String[] { "UserId", "Name", "Age", "Score", });
    internal_static_student_Students_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_student_Students_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_Students_descriptor,
        new String[] { "Student", });
    internal_static_student_Student_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_student_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_student_Student_descriptor,
        new String[] { "Id", "No", "Name", "Age", "Score", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
