// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: students.proto

package com.wkk.server.service.domain.grpc.student;

public interface StudentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:student.Students)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .student.Student student = 1;</code>
   */
  java.util.List<Student>
      getStudentList();
  /**
   * <code>repeated .student.Student student = 1;</code>
   */
  Student getStudent(int index);
  /**
   * <code>repeated .student.Student student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .student.Student student = 1;</code>
   */
  java.util.List<? extends StudentOrBuilder>
      getStudentOrBuilderList();
  /**
   * <code>repeated .student.Student student = 1;</code>
   */
  StudentOrBuilder getStudentOrBuilder(
      int index);
}
