// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: students.proto

package com.wkk.server.service.domain.grpc.student;

public interface StudentIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:student.StudentId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 studentId = 1;</code>
   */
  int getStudentId();
}
